import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {RoomState,MatchResult} from '@arena/shared';
import {testDatabase,testServer,registration,cookieFrom} from './helpers.js';
let database:Awaited<ReturnType<typeof testDatabase>>,server:Awaited<ReturnType<typeof testServer>>;
const people:{id:string;cookie:string}[]=[];
before(async()=>{database=await testDatabase();server=await testServer(database.db);for(let i=0;i<3;i++){const r=await server.request('/api/auth/register','POST',{...registration,email:`history${i}@example.com`,username:`history${i}`});people.push({id:(await r.json()).player.profile.id,cookie:cookieFrom(r)});}});
after(async()=>{await server?.close();await database?.close();});
function room():RoomState{return {id:randomUUID(),gameId:randomUUID(),name:'History arena',code:'ABC234',visibility:'PRIVATE',maxPlayers:4,status:'STARTING',hostPlayerProfileId:people[0]!.id,createdAt:new Date().toISOString(),players:people.slice(0,2).map((p,i)=>({playerProfileId:p.id,username:`history${i}`,displayName:`History ${i}`,ready:true,connected:true,isHost:i===0,joinedAt:new Date().toISOString()}))};}
async function result(){const r=room();const start=await server.matches.start(r);const value:MatchResult={matchId:r.gameId!,roomId:r.id,roomName:r.name,startedAt:start,endedAt:new Date(Date.parse(start)+180000).toISOString(),durationSeconds:180,endReason:'TIME_LIMIT',tied:false,winnerPlayerProfileId:people[0]!.id,standings:r.players.map((p,i)=>({playerProfileId:p.playerProfileId,username:p.username,displayName:p.displayName,score:i===0?2:0,eliminations:i===0?2:0,deaths:i===1?2:0,placement:i+1,isWinner:i===0,leftEarly:i===1}))};return {r,value};}
test('start retry retains one identity and participant set',async()=>{const {r,value}=await result();assert.equal(await server.matches.start(r),value.startedAt);assert.equal(await database.db.matchParticipant.count({where:{matchId:r.gameId}}),2);});
test('participant uniqueness is enforced by PostgreSQL',async()=>{const {value}=await result();const p=value.standings[0]!;await assert.rejects(database.db.matchParticipant.create({data:{matchId:value.matchId,participantKey:p.playerProfileId,playerProfileId:p.playerProfileId,username:p.username,displayName:p.displayName}}));assert.equal(await database.db.matchParticipant.count({where:{matchId:value.matchId}}),2);});
test('history orders newer completion times first',async()=>{const older=await result(),newer=await result();older.value.endedAt='2026-01-01T00:00:00.000Z';newer.value.endedAt='2026-01-02T00:00:00.000Z';await server.matches.finish(newer.value);await server.matches.finish(older.value);const ordered=await server.matches.list(people[0]!.id,25);assert.ok(ordered.findIndex(m=>m.matchId===newer.value.matchId)<ordered.findIndex(m=>m.matchId===older.value.matchId));});
test('concurrent finish is transactional and idempotent',async()=>{const {value}=await result();await Promise.all([server.matches.finish(value),server.matches.finish(value)]);const saved=await server.matches.detail(people[0]!.id,value.matchId);assert.deepEqual(saved,value);await server.matches.finish({...value,standings:value.standings.map(p=>({...p,score:99}))});assert.deepEqual(await server.matches.detail(people[0]!.id,value.matchId),value);});
test('incomplete standings roll back match status and participant changes',async()=>{const {value}=await result();await assert.rejects(server.matches.finish({...value,standings:value.standings.slice(0,1)}),/Incomplete/);assert.equal((await database.db.match.findUniqueOrThrow({where:{id:value.matchId}})).status,'IN_GAME');await server.matches.finish(value);});
test('history is authenticated, bounded, participant scoped and safely projected',async()=>{const {value}=await result();await server.matches.finish(value);assert.equal((await server.request('/api/matches')).status,401);const response=await server.request('/api/matches?limit=1','GET',undefined,people[0]!.cookie);assert.equal(response.status,200);const body=await response.json();assert.equal(body.matches.length,1);for(const forbidden of ['email','password','session','token','code'])assert.equal(JSON.stringify(body).includes(forbidden),false);assert.deepEqual((await (await server.request('/api/matches','GET',undefined,people[2]!.cookie)).json()).matches,[]);assert.equal((await server.request(`/api/matches/${value.matchId}`,'GET',undefined,people[2]!.cookie)).status,404);assert.equal((await server.request(`/api/matches/${value.matchId}`,'GET',undefined,people[1]!.cookie)).status,200);for(const query of ['limit=0','limit=26','limit=no','unknown=1'])assert.equal((await server.request(`/api/matches?${query}`,'GET',undefined,people[0]!.cookie)).status,400);assert.equal((await server.request('/api/matches/no','GET',undefined,people[0]!.cookie)).status,400);});
test('unfinished matches are excluded from history and detail',async()=>{const {value}=await result();assert.ok(!(await server.matches.list(people[0]!.id)).some(m=>m.matchId===value.matchId));await assert.rejects(server.matches.detail(people[0]!.id,value.matchId),/not found/);});
test('matchmade finish applies both rating changes exactly once with history snapshots',async()=>{
 const r=room();r.roomType='MATCHMAKING';const start=await server.matches.start(r);
 const value:MatchResult={matchId:r.gameId!,roomId:r.id,roomName:r.name,startedAt:start,endedAt:new Date(Date.parse(start)+180000).toISOString(),durationSeconds:180,endReason:'TIME_LIMIT',tied:false,winnerPlayerProfileId:people[0]!.id,standings:r.players.map((p,i)=>({playerProfileId:p.playerProfileId,username:p.username,displayName:p.displayName,score:1-i,eliminations:1-i,deaths:i,placement:i+1,isWinner:i===0,leftEarly:false}))};
 await Promise.all([server.matches.finish(value),server.matches.finish(value)]);await server.matches.finish(value);
 const saved=await server.matches.detail(people[0]!.id,value.matchId);assert.equal(saved.roomType,'MATCHMAKING');assert.deepEqual(saved.standings.map(p=>[p.ratingBefore,p.ratingAfter,p.ratingDelta]),[[1000,1016,16],[1000,984,-16]]);
 assert.equal(await server.matches.rating(people[0]!.id),1016);assert.equal(await server.matches.rating(people[1]!.id),984);
});
test('manual match completion leaves ratings unchanged and has no rating history fields',async()=>{const before=await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id)));const {value}=await result();const saved=await server.matches.finish(value);assert.ok(saved.standings.every(p=>p.ratingDelta===undefined));assert.deepEqual(await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id))),before);});
test('rated partial results roll back both profile and participant rating updates',async()=>{const r=room();r.roomType='MATCHMAKING';await server.matches.start(r);const {value}=await result();value.matchId=r.gameId!;value.standings=value.standings.slice(0,1);const before=await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id)));await assert.rejects(server.matches.finish(value));assert.deepEqual(await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id))),before);assert.ok((await database.db.matchParticipant.findMany({where:{matchId:r.gameId}})).every(p=>p.ratingAfter===null));assert.equal((await database.db.match.findUniqueOrThrow({where:{id:r.gameId}})).status,'IN_GAME');});
test('empty matchmade room does not award rating',async()=>{const r=room();r.roomType='MATCHMAKING';await server.matches.start(r);const {value}=await result();value.matchId=r.gameId!;value.endReason='EMPTY_ROOM';value.winnerPlayerProfileId=null;value.standings.forEach(p=>p.isWinner=false);const before=await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id)));await server.matches.finish(value);assert.deepEqual(await Promise.all(people.slice(0,2).map(p=>server.matches.rating(p.id))),before);});
test('deleted profiles retain historical participant snapshots',async()=>{const {value}=await result();await server.matches.finish(value);await database.db.playerProfile.delete({where:{id:people[1]!.id}});const saved=await server.matches.detail(people[0]!.id,value.matchId);assert.equal(saved.standings[1]!.displayName,'History 1');assert.equal((await database.db.matchParticipant.findUniqueOrThrow({where:{matchId_participantKey:{matchId:value.matchId,participantKey:people[1]!.id}}})).playerProfileId,null);});
