import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {MatchResult,RoomState} from '@arena/shared';
import {testDatabase,testServer,registration,cookieFrom} from './helpers.js';
let database:Awaited<ReturnType<typeof testDatabase>>,server:Awaited<ReturnType<typeof testServer>>;
const people:{id:string;cookie:string}[]=[];
before(async()=>{database=await testDatabase();server=await testServer(database.db);for(let i=0;i<4;i++){const r=await server.request('/api/auth/register','POST',{...registration,email:`stats${i}@example.com`,username:`stats${i}`});people.push({id:(await r.json()).player.profile.id,cookie:cookieFrom(r)});}});
after(async()=>{await server?.close();await database?.close();});
const summary=(i=0)=>server.matches.statistics.summary(people[i]!.id);
async function make(rated=true,tied=false,winner=0){
 const room:RoomState={id:randomUUID(),gameId:randomUUID(),name:'Stats arena',code:'ABC234',visibility:'PRIVATE',maxPlayers:2,status:'STARTING',hostPlayerProfileId:people[0]!.id,createdAt:new Date().toISOString(),roomType:rated?'MATCHMAKING':'MANUAL',players:people.slice(0,2).map((p,i)=>({playerProfileId:p.id,username:`stats${i}`,displayName:`Stats ${i}`,ready:true,connected:true,isHost:i===0,joinedAt:new Date().toISOString()}))};
 const start=await server.matches.start(room);
 const value:MatchResult={matchId:room.gameId!,roomId:room.id,roomName:room.name,startedAt:start,endedAt:new Date().toISOString(),durationSeconds:180,endReason:'TIME_LIMIT',tied,winnerPlayerProfileId:tied?null:people[winner]!.id,standings:room.players.map((p,i)=>({playerProfileId:p.playerProfileId,username:p.username,displayName:p.displayName,score:tied?0:i===winner?2:0,eliminations:tied?0:i===winner?2:0,deaths:tied?0:i===winner?0:2,placement:i+1,isWinner:tied||i===winner,leftEarly:i===1}))};return value;
}
test('registration creates persisted defaults and an unranked Silver summary',async()=>{const s=await summary();assert.equal(s.totalMatches,0);assert.equal(s.peakMmr,1000);assert.equal(s.mmr,1000);assert.equal(s.division.name,'Silver');assert.equal(s.rank,null);assert.equal(s.kd,0);assert.deepEqual(s.recentForm,[]);assert.equal(await database.db.playerStatistics.count(),4);});
test('rated winner and departed loser accumulate combat and outcomes exactly once concurrently',async()=>{const value=await make();await Promise.all([server.matches.finish(value),server.matches.finish(value)]);await server.matches.finish(value);const a=await summary(),b=await summary(1);assert.equal(a.ratedMatches,1);assert.equal(a.totalMatches,1);assert.equal(a.wins,1);assert.equal(a.eliminations,2);assert.equal(a.peakMmr,1016);assert.equal(a.currentWinStreak,1);assert.equal(b.losses,1);assert.equal(b.deaths,2);assert.equal(b.mmr,984);assert.equal(a.rank,1);assert.equal(b.rank,2);});
test('second win increases current and best streak and peak',async()=>{await server.matches.finish(await make());const s=await summary();assert.equal(s.currentWinStreak,2);assert.equal(s.bestWinStreak,2);assert.ok(s.peakMmr>1016);assert.equal(s.peakMmr,s.mmr);});
test('tie resets streak and retains peak',async()=>{const before=await summary();await server.matches.finish(await make(true,true));const s=await summary();assert.equal(s.ties,1);assert.equal(s.currentWinStreak,0);assert.equal(s.bestWinStreak,2);assert.equal(s.peakMmr,before.peakMmr);assert.ok(s.mmr<before.mmr);});
test('loss resets win streak and never decreases peak',async()=>{await server.matches.finish(await make());const before=await summary();await server.matches.finish(await make(true,false,1));const s=await summary();assert.equal(s.losses,1);assert.equal(s.currentWinStreak,0);assert.equal(s.peakMmr,before.peakMmr);});
test('manual games change only overall counters, preserve all ranked metrics and form',async()=>{const before=await summary();await server.matches.finish(await make(false));const s=await summary();for(const key of ['mmr','peakMmr','ratedMatches','wins','losses','ties','eliminations','deaths','currentWinStreak','bestWinStreak','rank','recentForm'] as const)assert.deepEqual(s[key],before[key],key);assert.equal(s.totalMatches,before.totalMatches+1);assert.equal(s.unratedMatches,1);assert.equal(s.overallEliminations,before.overallEliminations+2);});
test('recent form returns five rated results newest first and excludes manual',async()=>{const s=await summary();assert.equal(s.recentForm.length,5);assert.deepEqual(s.recentForm.map(r=>r.outcome),['L','W','T','W','W']);assert.ok(s.recentForm.every((r,i,a)=>!i||r.endedAt<=a[i-1]!.endedAt));});
test('empty-room abandonments do not count toward any statistics',async()=>{const before=await summary(),value=await make();value.endReason='EMPTY_ROOM';value.winnerPlayerProfileId=null;value.standings.forEach(p=>p.isWinner=false);await server.matches.finish(value);assert.deepEqual(await summary(),before);});
test('invalid participant rolls back MMR, stats and results, then retry applies once',async()=>{const before=await summary(),value=await make();await assert.rejects(server.matches.finish({...value,standings:[value.standings[0]!,{...value.standings[1]!,playerProfileId:randomUUID()}]}));assert.deepEqual(await summary(),before);assert.equal((await database.db.match.findUniqueOrThrow({where:{id:value.matchId}})).status,'IN_GAME');await server.matches.finish(value);await server.matches.finish(value);assert.equal((await summary()).ratedMatches,before.ratedMatches+1);});
test('failure during statistics writes rolls back prior statistics, rating and claim',async()=>{
 const before=await summary(),value=await make(),last=people.slice(0,2).map(p=>p.id).sort()[1]!;
 await database.db.$executeRawUnsafe(`CREATE FUNCTION fail_stats_write() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected stats failure'; END $$`);
 await database.db.$executeRawUnsafe(`CREATE TRIGGER fail_stats BEFORE UPDATE ON "PlayerStatistics" FOR EACH ROW WHEN (NEW."playerProfileId"='${last}'::uuid) EXECUTE FUNCTION fail_stats_write()`);
 try{await assert.rejects(server.matches.finish(value));assert.deepEqual(await summary(),before);assert.equal((await database.db.match.findUniqueOrThrow({where:{id:value.matchId}})).status,'IN_GAME');assert.ok((await database.db.matchParticipant.findMany({where:{matchId:value.matchId}})).every(p=>p.ratingAfter===null));}
 finally{await database.db.$executeRawUnsafe('DROP TRIGGER fail_stats ON "PlayerStatistics"');await database.db.$executeRawUnsafe('DROP FUNCTION fail_stats_write()');}
 await server.matches.finish(value);assert.equal((await summary()).ratedMatches,before.ratedMatches+1);
});
test('parallel manual matches do not lose career increments',async()=>{const before=await summary();const values=await Promise.all([make(false),make(false)]);await Promise.all(values.map(v=>server.matches.finish(v)));assert.equal((await summary()).totalMatches,before.totalMatches+2);});
test('leaderboard and personal statistics require authentication',async()=>{for(const path of ['/api/leaderboard','/api/statistics/me'])assert.equal((await server.request(path)).status,401);});
test('pagination rejects malformed, unbounded and unknown parameters',async()=>{for(const q of ['page=0','page=-1','page=100001','page=1.5','limit=0','limit=51','limit=no','page=1&page=2','rating=5000'])assert.equal((await server.request(`/api/leaderboard?${q}`,'GET',undefined,people[0]!.cookie)).status,400,q);assert.equal((await server.request('/api/statistics/me?playerId=someone','GET',undefined,people[0]!.cookie)).status,400);});
test('bounded page returns off-page personal rank, excludes unrated users and exposes only public data',async()=>{const r=await server.request('/api/leaderboard?page=2&limit=1','GET',undefined,people[0]!.cookie);assert.equal(r.status,200);const body=await r.json();assert.equal(body.players.length,1);assert.equal(body.players[0].rank,2);assert.equal(body.total,2);assert.equal(body.ownRank,1);for(const field of ['email','password','session','token','userId','username'])assert.equal(JSON.stringify(body).includes(field),false);assert.equal((await server.matches.statistics.leaderboard(people[2]!.id)).ownRank,null);assert.deepEqual((await server.matches.statistics.leaderboard(people[0]!.id,10,25)).players,[]);});
test('clients cannot write competitive counters through profile or dedicated routes',async()=>{assert.equal((await server.request('/api/profile','PATCH',{displayName:'Cheat',rating:5000,wins:10},people[0]!.cookie)).status,400);assert.equal((await server.request('/api/statistics/me','POST',{wins:10},people[0]!.cookie)).status,404);});
test('ranking uses MMR, wins, win rate and stable UUID consistently with own rank',async()=>{
 for(let i=0;i<4;i++){await database.db.playerProfile.update({where:{id:people[i]!.id},data:{rating:i===0?1200:1100}});await database.db.playerStatistics.update({where:{playerProfileId:people[i]!.id},data:{ratedMatches:i===1?10:5,ratedWins:i===0?1:2}});}
 let board=await server.matches.statistics.leaderboard(people[1]!.id);assert.equal(board.players[0]!.playerProfileId,people[0]!.id);assert.deepEqual(board.players.slice(1,3).map(p=>p.playerProfileId),[people[2]!.id,people[3]!.id].sort());assert.equal(board.players[3]!.playerProfileId,people[1]!.id);assert.equal(board.ownRank,4);
 await database.db.playerStatistics.update({where:{playerProfileId:people[1]!.id},data:{ratedWins:3}});board=await server.matches.statistics.leaderboard(people[1]!.id);assert.equal(board.ownRank,2);assert.equal(board.players[1]!.playerProfileId,people[1]!.id);
});
