import { createServer } from "node:http";
import { createApp } from "./app.js";
import { env } from "./config/env.js";
import { createOptionalRedis } from "./config/redis.js";
import { attachSocketServer } from "./socket/index.js";
import { logger } from "./utils/logger.js";
import { createDatabase } from "./config/database.js";
import { createAuthService } from "./services/auth.js";
if (!env.databaseUrl) throw new Error("DATABASE_URL is required");
const db = createDatabase(env.databaseUrl);
const auth = createAuthService(db, env);
const cleanup = () => { void auth.cleanupExpired().catch(() => logger.warn("sessions.cleanup_failed")); };
const cleanupInterval = setInterval(cleanup, 60 * 60 * 1000).unref();
cleanup();
const redis = createOptionalRedis(env.redisUrl);
const server = createServer(createApp(env, auth, () => redis.status));
const io = attachSocketServer(server, env, auth);
server.on("error", error => { logger.error("server.failed", { message: error.message }); redis.close(); process.exitCode = 1; });
server.listen(env.port, () => { logger.info("server.listening", { port: env.port }); void redis.connect(); });
let stopping = false;
function shutdown() {
 if (stopping) return;
 stopping = true;
 logger.info("server.stopping");
 const timeout = setTimeout(() => process.exit(1), 5000).unref();
 clearInterval(cleanupInterval);
 redis.close();
 io.close(() => { void db.$disconnect().finally(() => { clearTimeout(timeout); process.exitCode = 0; }); });
}
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);
